### PR TITLE
Reskin and fix final screen

### LINKED ISSUE #4: Make phone numbers clickable
* Phone numbers as tappable  links

### PR DESCRIPTION
**Pull request by Sirage-t**
Fixes #4, #6, #14, #18, and #21.

### CODE REVIEW

**Comment by mferrare** [comment]
What follows in this comment and subsequent comments is feedback and not a prerequisite to approving this PR.

Is line 14 (define `CLCSA_ManagerStore`) redundant?

**Comment by mferrare** [comment]
Prefer to break line 20 of `main.yml` (`CLCSA_matchedServicesFlattened = [v if len(s.variants) > 0 else s for s in CLCSA_matchedServices for v in s.variants ]`) into a regular if/for loop.  Except for you and me most people coming into the Lab won't understand that form of python syntax.

**Comment by mferrare** [comment]
Why in line 24 of `Config_Store.yml` is the location for Northern Community Legal Service set to `IsNot="North"`?  Shouldn't it be `Is="North"`?

UPDATE: Fixed to `Is="North"`

**Comment by mferrare** [comment]
Gender selection looks like this:
image

**Comment by mferrare** [comment]
If I input the following:
- Domestic Violence
- South
- Not Aboriginal
- Female

I would expect to see a list with INDIO and Women's legal centre at the top.  However, as 2nd and third results I get JusticeNet and Refugee Advocacy, neither of which deal with DV.  Women's Legal Service doesn't appear.

image

**Review by mferrare — CHANGES_REQUESTED** [review]
See comments in the PR for feedback but also see issues #26 and #27 which need to be fixed before this can be signed off.

**Comment by Sirage-t** [comment]
> Prefer to break line 20 of `main.yml` (`CLCSA_matchedServicesFlattened = [v if len(s.variants) > 0 else s for s in CLCSA_matchedServices for v in s.variants ]`) into a regular if/for loop. Except for you and me most people coming into the Lab won't understand that form of python syntax.

List comprehension is more performant

**Comment by Sirage-t** [comment]
> What follows in this comment and subsequent comments is feedback and not a prerequisite to approving this PR.
> 
> Is line 14 (define `CLCSA_ManagerStore`) redundant?

No. I am just creating a shorter reference to the store object so I don't have to type `CLCSA_ManagerDirectory.store` in question blocks and final screen.

**Review by mferrare — APPROVED** [review]
All good! Thanks @Sirage-t

**Pull request merged**
